### ISSUE TITLE
Extend groups

### ISSUE THREAD

**Issue by venelinn** [vkbansal/gulp-group-files#1]
Hi, 
I have two questions
1. Is there a way to extend a group/array into another group/array?
2. Is there a way to include js/css/scss in one array? Something like this
   `'bootstrap':[
       'bootstrap/bootstrap.js',
       'bootstrap/bootstrap.scss'
   ]`

Thanks !

**Comment by vkbansal** [comment]
> Is there a way to extend a group/array into another group/array?

I'm unable understand this question. Can you give an example?

> Is there a way to include js/css/scss in one array? Something like this 'bootstrap':[ 'bootstrap/bootstrap.js', 'bootstrap/bootstrap.scss' ]

Yes you must be able to it since the plugin is not based on extensions but the group itself.

**Comment by venelinn** [comment]
_Is there a way to extend a group/array into another group/array?_
So let me give you an example with my WRO4j configuration that I wanna replace with your plugin.

http://pastebin.com/dPX4z4mz

As you can see I have group **sweetAlert** that I'm including in other group(s). Similar to your array.

**Comment by vkbansal** [comment]
You can do something like this

``` js
var sweetAlert = [
    'resources/js/common.js',
    'resources/css/sweet-alert.css'
];
var scripts = {
    sweetAlert: sweetAlert,
    'bootstrap':sweetAlert.concat([
        'resources/js/bootstrap-transition.js',
        'resources/js/bootstrap-multiselect.js'
    ])
};
```
